### ISSUE TITLE
issue with paging of the geocodable results

### ISSUE THREAD

**Issue by edmond1984** [mariano/geocode#1]
Amazing plugin mariano!
But i'm experiencing this problem with the paging
I'm passing some params in the paging with $paginator->options( 
          array('url'=>$this->passedArgs)); 
but it automatically adds the param 'near' to the url without asking for it (this messes up some unnamed params of my controller page)
so the url of page 'next" is: 
../index/near/page:2
while near should not be there in the URL
is there any way to remove this?
because when clicking af another times on 'next' gives this url
.../index/near/near/page:6/location:90210/country:US

**Comment by mariano** [comment]
wow this is really weird, you just specify the custom 'near' find type in the paginator options and its adding that? You may have found a cake bug.

Can you bin the controller action fully, and the view?

**Comment by mariano** [comment]
Also, try something for me, instead of specifying the 'url' override in the view with $paginator->options(), do it at the controller in the $this->paginate setting.

**Comment by mariano** [comment]
Reopen ticket when you have some feedback, thanks!

**Comment by edmond1984** [comment]
Ok, sorry for the delay of my reply. I tried your suggestion but it still has the same result

**Comment by edmond1984** [comment]
I've binned my controller and view in the following url www.dezov.be/index.rar
